name: Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.32.5'

      - name: Install dependencies
        run: flutter pub get
      
      - name: Activate FastForge
        run: dart pub global activate fastforge

      - name: Build linux and android packages
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build libgtk-3-dev locate libsqlite3-dev fuse libfuse2
          sudo updatedbs
          fastforge release --name=linux
          fastforge release --name=android
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-linux-android
          path: |
            dist/*/*
