display_name: Flip
package_name: flip

maintainer:
  name: "anubhavkrishna1"
  email: "anubhavkrishna1@users.noreply.github.com"

priority: optional

section: x11

installed_size: 14410

essential: false

icon: assets/logo_256.png

description: |
  A clipboard sync application that enables sharing clipboard content across devices on your local network using WebSockets.

postuninstall_scripts:
  - echo "Sorry to see you go."

keywords:
  - clipboard
  - sync
  - network
  - websocket
  - sharing

generic_name: Clipboard Sync

categories:
  - Development
  - Utility

startup_notify: true
